---

- name: Show current version of lab switches
  hosts: DC1_L3_LEAVES
  gather_facts: no

  tasks:

    - name: run show version on remote devices
      arista.eos.eos_command:
        commands: show version
      register: version

    - name: Print version number
      ansible.builtin.debug:
        msg:
        - The EOS version of "{{ inventory_hostname }}" is "{{ version["stdout_lines"][0][6] }}"