---

name: Verify EOS version


on:
  push:


jobs:
  show_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print output
        run: echo Checking EOS Version now!

      - name: install ansible
        run: |
          sudo apt install ansible
          pip install ansible-pylibssh

      - name: show_version.yml
        run: ansible-playbook playbooks/show_version.yml
